<?php

declare(strict_types=1);

namespace MarekSkopal\TwelveData\Dto\Fundamentals;

/**
 * @phpstan-type CashFlowConsolidatedCashFlowFromOperatingActivitiesType array{
 *     net_income_from_continuing_operations: int,
 *     operating_cash_flow?: int,
 *     cash_flow_from_continuing_operating_activities?: int,
 *     cash_from_discontinued_operating_activities?: int,
 *     cash_flow_from_discontinued_operation?: int,
 *     free_cash_flow?: int,
 *     cash_flows_from_used_in_operating_activities_direct?: int,
 *     taxes_refund_paid?: int,
 *     taxes_refund_paid_direct?: int,
 *     interest_received?: int,
 *     interest_received_direct?: int,
 *     interest_paid?: int,
 *     interest_paid_direct?: int,
 *     dividend_received?: int,
 *     dividend_received_direct?: int,
 *     dividend_paid?: int,
 *     dividend_paid_direct?: int,
 *     change_in_working_capital?: int,
 *     change_in_other_working_capital?: int,
 *     change_in_receivables?: int,
 *     changes_in_account_receivables?: int,
 *     change_in_payables_and_accrued_expense?: int,
 *     change_in_accrued_expense?: int,
 *     change_in_payable?: int,
 *     change_in_dividend_payable?: int,
 *     change_in_account_payable?: int,
 *     change_in_tax_payable?: int,
 *     change_in_income_tax_payable?: int,
 *     change_in_interest_payable?: int,
 *     change_in_other_current_liabilities?: int,
 *     change_in_other_current_assets?: int,
 *     change_in_inventory?: int,
 *     change_in_prepaid_assets?: int,
 *     other_non_cash_items?: int,
 *     excess_tax_benefit_from_stock_based_compensation?: int,
 *     stock_based_compensation?: int,
 *     unrealized_gain_loss_on_investment_securities?: int,
 *     provision_and_write_off_of_assets?: int,
 *     asset_impairment_charge?: int,
 *     amortization_of_securities?: int,
 *     deferred_tax?: int,
 *     deferred_income_tax?: int,
 *     depreciation_amortization_depletion?: int,
 *     depletion?: int,
 *     depreciation_and_amortization?: int,
 *     amortization_cash_flow?: int,
 *     amortization_of_intangibles?: int,
 *     depreciation?: int,
 *     operating_gains_losses?: int,
 *     pension_and_employee_benefit_expense?: int,
 *     earnings_losses_from_equity_investments?: int,
 *     gain_loss_on_investment_securities?: int,
 *     net_foreign_currency_exchange_gain_loss?: int,
 *     gain_loss_on_sale_of_ppe?: int,
 *     gain_loss_on_sale_of_business?: int,
 * }
 */
readonly class CashFlowConsolidatedCashFlowFromOperatingActivities
{
    public function __construct(
        public int $netIncomeFromContinuingOperations,
        public ?int $operatingCashFlow,
        public ?int $cashFlowFromContinuingOperatingActivities,
        public ?int $cashFromDiscontinuedOperatingActivities,
        public ?int $cashFlowFromDiscontinuedOperation,
        public ?int $freeCashFlow,
        public ?int $cashFlowsFromUsedInOperatingActivitiesDirect,
        public ?int $taxesRefundPaid,
        public ?int $taxesRefundPaidDirect,
        public ?int $interestReceived,
        public ?int $interestReceivedDirect,
        public ?int $interestPaid,
        public ?int $interestPaidDirect,
        public ?int $dividendReceived,
        public ?int $dividendReceivedDirect,
        public ?int $dividendPaid,
        public ?int $dividendPaidDirect,
        public ?int $changeInWorkingCapital,
        public ?int $changeInOtherWorkingCapital,
        public ?int $changeInReceivables,
        public ?int $changesInAccountReceivables,
        public ?int $changeInPayablesAndAccruedExpense,
        public ?int $changeInAccruedExpense,
        public ?int $changeInPayable,
        public ?int $changeInDividendPayable,
        public ?int $changeInAccountPayable,
        public ?int $changeInTaxPayable,
        public ?int $changeInIncomeTaxPayable,
        public ?int $changeInInterestPayable,
        public ?int $changeInOtherCurrentLiabilities,
        public ?int $changeInOtherCurrentAssets,
        public ?int $changeInInventory,
        public ?int $changeInPrepaidAssets,
        public ?int $otherNonCashItems,
        public ?int $excessTaxBenefitFromStockBasedCompensation,
        public ?int $stockBasedCompensation,
        public ?int $unrealizedGainLossOnInvestmentSecurities,
        public ?int $provisionAndWriteOffOfAssets,
        public ?int $assetImpairmentCharge,
        public ?int $amortizationOfSecurities,
        public ?int $deferredTax,
        public ?int $deferredIncomeTax,
        public ?int $depreciationAmortizationDepletion,
        public ?int $depletion,
        public ?int $depreciationAndAmortization,
        public ?int $amortizationCashFlow,
        public ?int $amortizationOfIntangibles,
        public ?int $depreciation,
        public ?int $operatingGainsLosses,
        public ?int $pensionAndEmployeeBenefitExpense,
        public ?int $earningsLossesFromEquityInvestments,
        public ?int $gainLossOnInvestmentSecurities,
        public ?int $netForeignCurrencyExchangeGainLoss,
        public ?int $gainLossOnSaleOfPpe,
        public ?int $gainLossOnSaleOfBusiness,
    )
    {
    }

    /** @param CashFlowConsolidatedCashFlowFromOperatingActivitiesType $data */
    public static function fromArray(array $data): self
    {
        return new self(
            netIncomeFromContinuingOperations: $data['net_income_from_continuing_operations'],
            operatingCashFlow: $data['operating_cash_flow'] ?? null,
            cashFlowFromContinuingOperatingActivities: $data['cash_flow_from_continuing_operating_activities'] ?? null,
            cashFromDiscontinuedOperatingActivities: $data['cash_from_discontinued_operating_activities'] ?? null,
            cashFlowFromDiscontinuedOperation: $data['cash_flow_from_discontinued_operation'] ?? null,
            freeCashFlow: $data['free_cash_flow'] ?? null,
            cashFlowsFromUsedInOperatingActivitiesDirect: $data['cash_flows_from_used_in_operating_activities_direct'] ?? null,
            taxesRefundPaid: $data['taxes_refund_paid'] ?? null,
            taxesRefundPaidDirect: $data['taxes_refund_paid_direct'] ?? null,
            interestReceived: $data['interest_received'] ?? null,
            interestReceivedDirect: $data['interest_received_direct'] ?? null,
            interestPaid: $data['interest_paid'] ?? null,
            interestPaidDirect: $data['interest_paid_direct'] ?? null,
            dividendReceived: $data['dividend_received'] ?? null,
            dividendReceivedDirect: $data['dividend_received_direct'] ?? null,
            dividendPaid: $data['dividend_paid'] ?? null,
            dividendPaidDirect: $data['dividend_paid_direct'] ?? null,
            changeInWorkingCapital: $data['change_in_working_capital'] ?? null,
            changeInOtherWorkingCapital: $data['change_in_other_working_capital'] ?? null,
            changeInReceivables: $data['change_in_receivables'] ?? null,
            changesInAccountReceivables: $data['changes_in_account_receivables'] ?? null,
            changeInPayablesAndAccruedExpense: $data['change_in_payables_and_accrued_expense'] ?? null,
            changeInAccruedExpense: $data['change_in_accrued_expense'] ?? null,
            changeInPayable: $data['change_in_payable'] ?? null,
            changeInDividendPayable: $data['change_in_dividend_payable'] ?? null,
            changeInAccountPayable: $data['change_in_account_payable'] ?? null,
            changeInTaxPayable: $data['change_in_tax_payable'] ?? null,
            changeInIncomeTaxPayable: $data['change_in_income_tax_payable'] ?? null,
            changeInInterestPayable: $data['change_in_interest_payable'] ?? null,
            changeInOtherCurrentLiabilities: $data['change_in_other_current_liabilities'] ?? null,
            changeInOtherCurrentAssets: $data['change_in_other_current_assets'] ?? null,
            changeInInventory: $data['change_in_inventory'] ?? null,
            changeInPrepaidAssets: $data['change_in_prepaid_assets'] ?? null,
            otherNonCashItems: $data['other_non_cash_items'] ?? null,
            excessTaxBenefitFromStockBasedCompensation: $data['excess_tax_benefit_from_stock_based_compensation'] ?? null,
            stockBasedCompensation: $data['stock_based_compensation'] ?? null,
            unrealizedGainLossOnInvestmentSecurities: $data['unrealized_gain_loss_on_investment_securities'] ?? null,
            provisionAndWriteOffOfAssets: $data['provision_and_write_off_of_assets'] ?? null,
            assetImpairmentCharge: $data['asset_impairment_charge'] ?? null,
            amortizationOfSecurities: $data['amortization_of_securities'] ?? null,
            deferredTax: $data['deferred_tax'] ?? null,
            deferredIncomeTax: $data['deferred_income_tax'] ?? null,
            depreciationAmortizationDepletion: $data['depreciation_amortization_depletion'] ?? null,
            depletion: $data['depletion'] ?? null,
            depreciationAndAmortization: $data['depreciation_and_amortization'] ?? null,
            amortizationCashFlow: $data['amortization_cash_flow'] ?? null,
            amortizationOfIntangibles: $data['amortization_of_intangibles'] ?? null,
            depreciation: $data['depreciation'] ?? null,
            operatingGainsLosses: $data['operating_gains_losses'] ?? null,
            pensionAndEmployeeBenefitExpense: $data['pension_and_employee_benefit_expense'] ?? null,
            earningsLossesFromEquityInvestments: $data['earnings_losses_from_equity_investments'] ?? null,
            gainLossOnInvestmentSecurities: $data['gain_loss_on_investment_securities'] ?? null,
            netForeignCurrencyExchangeGainLoss: $data['net_foreign_currency_exchange_gain_loss'] ?? null,
            gainLossOnSaleOfPpe: $data['gain_loss_on_sale_of_ppe'] ?? null,
            gainLossOnSaleOfBusiness: $data['gain_loss_on_sale_of_business'] ?? null,
        );
    }
}
