<?php

declare(strict_types=1);

namespace MarekSkopal\TwelveData\Dto\TechnicalIndicators;

/**
 * @phpstan-type MetaIndicatorType array{
 *     name: string,
 *     series_type?: string,
 *     time_period?: int,
 *     sd?: int,
 *     sd_time_period?: int,
 *     ma_type?: string,
 *     conversion_line_period?: int,
 *     base_line_period?: int,
 *     leading_span_b_period?: int,
 *     lagging_span_period?: int,
 *     include_ahead_span_period?: bool,
 *     fast_limit?: float,
 *     slow_limit?: float,
 *     acceleration?: float,
 *     maximum?: float,
 *     start_value?: float,
 *     offset_on_reverse?: float,
 *     acceleration_limit_long?: float,
 *     acceleration_long?: float,
 *     acceleration_max_long?: float,
 *     acceleration_limit_short?: float,
 *     acceleration_short?: float,
 *     acceleration_max_short?: float,
 *     fast_period?: int,
 *     fast_ma_type?: string,
 *     slow_period?: int,
 *     slow_ma_type?: string,
 *     long_roc_period?: int,
 *     short_roc_period?: int,
 *     wma_period?: int,
 *     centered?: bool,
 *     rsi_period?: int,
 *     up_down_length?: int,
 *     percent_rank_period?: int,
 *     roc_period_1?: int,
 *     roc_period_2?: int,
 *     roc_period_3?: int,
 *     roc_period_4?: int,
 *     sma_period_1?: int,
 *     sma_period_2?: int,
 *     sma_period_3?: int,
 *     sma_period_4?: int,
 *     signal_period?: int,
 *     signal_ma_type?: string,
 * }
 */
readonly class MetaIndicator
{
    public function __construct(
        public string $name,
        public ?string $seriesType,
        public ?int $timePeriod,
        public ?int $sd,
        public ?int $sdTimePeriod,
        public ?string $maType,
        public ?int $conversionLinePeriod,
        public ?int $base_line_period,
        public ?int $leading_span_b_period,
        public ?int $laggingSpanPeriod,
        public ?bool $includeAheadSpanPeriod,
        public ?float $fastLimit,
        public ?float $slowLimit,
        public ?float $acceleration,
        public ?float $maximum,
        public ?float $startValue,
        public ?float $offsetOnReverse,
        public ?float $accelerationLimitLong,
        public ?float $accelerationLong,
        public ?float $accelerationMaxLong,
        public ?float $accelerationLimitShort,
        public ?float $accelerationShort,
        public ?float $accelerationMaxShort,
        public ?int $fastPeriod,
        public ?string $fastMaType,
        public ?int $slowPeriod,
        public ?string $slowMaType,
        public ?int $longRocPeriod,
        public ?int $shortRocPeriod,
        public ?int $wmaPeriod,
        public ?bool $centered,
        public ?int $rsiPeriod,
        public ?int $upDownLength,
        public ?int $percentRankPeriod,
        public ?int $rocPeriod1,
        public ?int $rocPeriod2,
        public ?int $rocPeriod3,
        public ?int $rocPeriod4,
        public ?int $smaPeriod1,
        public ?int $smaPeriod2,
        public ?int $smaPeriod3,
        public ?int $smaPeriod4,
        public ?int $signalPeriod,
        public ?string $signalMaType,
    ) {
    }

    /** @param MetaIndicatorType $data */
    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            seriesType: $data['series_type'] ?? null,
            timePeriod: $data['time_period'] ?? null,
            sd: $data['sd'] ?? null,
            sdTimePeriod: $data['sd_time_period'] ?? null,
            maType: $data['ma_type'] ?? null,
            conversionLinePeriod: $data['conversion_line_period'] ?? null,
            base_line_period: $data['base_line_period'] ?? null,
            leading_span_b_period: $data['leading_span_b_period'] ?? null,
            laggingSpanPeriod: $data['lagging_span_period'] ?? null,
            includeAheadSpanPeriod: $data['include_ahead_span_period'] ?? null,
            fastLimit: $data['fast_limit'] ?? null,
            slowLimit: $data['slow_limit'] ?? null,
            acceleration: $data['acceleration'] ?? null,
            maximum: $data['maximum'] ?? null,
            startValue: $data['start_value'] ?? null,
            offsetOnReverse: $data['offset_on_reverse'] ?? null,
            accelerationLimitLong: $data['acceleration_limit_long'] ?? null,
            accelerationLong: $data['acceleration_long'] ?? null,
            accelerationMaxLong: $data['acceleration_max_long'] ?? null,
            accelerationLimitShort: $data['acceleration_limit_short'] ?? null,
            accelerationShort: $data['acceleration_short'] ?? null,
            accelerationMaxShort: $data['acceleration_max_short'] ?? null,
            fastPeriod: $data['fast_period'] ?? null,
            fastMaType: $data['fast_ma_type'] ?? null,
            slowPeriod: $data['slow_period'] ?? null,
            slowMaType: $data['slow_ma_type'] ?? null,
            longRocPeriod: $data['long_roc_period'] ?? null,
            shortRocPeriod: $data['short_roc_period'] ?? null,
            wmaPeriod: $data['wma_period'] ?? null,
            centered: $data['centered'] ?? null,
            rsiPeriod: $data['rsi_period'] ?? null,
            upDownLength: $data['up_down_length'] ?? null,
            percentRankPeriod: $data['percent_rank_period'] ?? null,
            rocPeriod1: $data['roc_period_1'] ?? null,
            rocPeriod2: $data['roc_period_2'] ?? null,
            rocPeriod3: $data['roc_period_3'] ?? null,
            rocPeriod4: $data['roc_period_4'] ?? null,
            smaPeriod1: $data['sma_period_1'] ?? null,
            smaPeriod2: $data['sma_period_2'] ?? null,
            smaPeriod3: $data['sma_period_3'] ?? null,
            smaPeriod4: $data['sma_period_4'] ?? null,
            signalPeriod: $data['signal_period'] ?? null,
            signalMaType: $data['signal_ma_type'] ?? null,
        );
    }
}
